/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as CanvasRouteRouteImport } from './routes/canvas/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanvasIndexRouteImport } from './routes/canvas/index'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRouteRoute = CanvasRouteRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CanvasRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/canvas/': typeof CanvasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteRoute
  '/canvas': typeof CanvasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/canvas/': typeof CanvasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/canvas' | '/login' | '/canvas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/canvas'
  id: '__root__' | '/' | '/canvas' | '/login' | '/canvas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRouteRoute: typeof CanvasRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/'
      fullPath: '/canvas/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof CanvasRouteRoute
    }
  }
}

interface CanvasRouteRouteChildren {
  CanvasIndexRoute: typeof CanvasIndexRoute
}

const CanvasRouteRouteChildren: CanvasRouteRouteChildren = {
  CanvasIndexRoute: CanvasIndexRoute,
}

const CanvasRouteRouteWithChildren = CanvasRouteRoute._addFileChildren(
  CanvasRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRouteRoute: CanvasRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
