FROM node:24-slim AS base
RUN npm install -g pnpm turbo
WORKDIR /app

FROM base AS pruner
COPY . .
RUN turbo prune api --docker

FROM base AS dev
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile --ignore-scripts

# 소스 파일 복사 및 @repo/api 빌드
COPY --from=pruner /app/out/full/ .
RUN pnpm --filter @repo/api build

EXPOSE 3000
CMD ["pnpm", "--filter", "api", "dev"]